### ISSUE TITLE
Receiving a callback when a Toast is tapped

### ISSUE THREAD

**Issue by EvanWieland** [Telerik-Verified-Plugins/Toast#1]
Receiving a callback when a Toast is tapped doesn't seem to be working at all. Am I the only one with this issue?

**Comment by EddyVerbruggen** [comment]
Please elaborate,  preferrably with a testproject.

**Comment by EvanWieland** [comment]
I may be missing something but I'm not sure what it would be. I pretty much copy and pasted your demo code and I can't get the tap for callback to work. The toast launch works great tho. Here is a demo of what I'm trying to do. [https://github.com/EvanWieland/Toast-DemoApp.git](https://github.com/EvanWieland/Toast-DemoApp.git)

**Comment by EddyVerbruggen** [comment]
@EvanWieland you should update to 2.3.2, so change [this line here](https://github.com/EvanWieland/Toast-DemoApp/blob/master/Toast-PhoneGap-Plugin-DemoApp/.abproject#L20) or go into AppBuilder and update to the latest version of the Verified Plugins Marketplace.

The reason is you're now on 2.2.x, while this feature was added in 2.3.0 and further tweaked for Android on 2.3.2.

**Comment by EvanWieland** [comment]
Sorry, should have checked that! I hate to be a bother, but that still doesn't seem to work, even after the upgrade. Do you have a working example of the tap for callback I could see?

**Comment by EddyVerbruggen** [comment]
No worries - which platform are we talking about, iOS or Android? Your code seems ok btw, did you do a full rebuild and deployed the binary to your phone?

**Comment by EvanWieland** [comment]
Currently I'm debugging on Android. I actually uninstalled and rebuilt twice to make sure that the new plugin was included. I'm going to test it on iOS quick to see if it does anything different.

**Comment by EvanWieland** [comment]
Yeah, same thing on iOS.

**Comment by EddyVerbruggen** [comment]
So you're looking at the console when tapping a toast?

**Comment by EvanWieland** [comment]
Yeah. "The toast has been shown" console.log is executed immediately when the toast is shown, and when I tap the toast nothing logs.

**Comment by EddyVerbruggen** [comment]
It seems like the demo app wasn't really up to date and so your fork has a bundled plugin in the plugins folder. Can you remove that, as it overrides any referenced plugin in package.json with the same id.

I just did that [here](https://github.com/Telerik-Verified-Plugins/Toast-DemoApp/commit/1f3508b3af0250dbf6fda2e1eab0a40fb224b535) in the upstream. Sorry for the inconvenience!

**Comment by EvanWieland** [comment]
I went ahead and rebuilt the repository with your changes. Should that be working then?
